# fly.toml app configuration file generated for discord-ai-bro on 2025-05-14T08:59:30-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-ai-bro'
primary_region = 'dfw'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[env]
  PYTHONUNBUFFERED = '1'

[processes]
  app = 'python bot.py'

[checks]
  [checks.health]
    port = 8080
    type = 'http'
    interval = '30s'
    timeout = '5s'
    grace_period = '5s'
    method = 'get'
    path = '/health'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
